### PR TITLE
uploaded Cheatsheet.pdf

### PR DESCRIPTION
**Pull request by jhk0530**
Hi, 

I made cheatsheet pdf file. `cheatsheet.pdf`

it looks like this.
image

* I used template from [here](https://rstudio.com/resources/cheatsheets/how-to-contribute-a-cheatsheet/)

* So please check contents, including the licence ( CC BY SA in template )

* I changed example code from `readme`, it's little bit different with expected.
* I didn't mention about `butler`. (waiter said it's deprecated)
* changed main color theme from blue~~~ to "waiter color theme"

* If you allow we can submit to rstudio's cheatsheet [lists](https://rstudio.com/resources/cheatsheets/) as contributed cheat sheets.
 
* welcome for fix, suggestion, comment.

### CODE REVIEW

**Comment by JohnCoene** [comment]
Thank you very much for this, it looks great! I wanted to add this in #39 but could not bring myself to do it.

Two things:

1. could you share the ppt version with me jcoenep[at]gmail.com in case changes need to be made in the future
2. Please add yourself as `ctb` in the `DESCRIPTION` (if you want)

Thanks again!

**Comment by JohnCoene** [comment]
Oh also real quick, could you add `cheatsheet.pdf` to `.Rbuildignore`.

```r
usethis::use_build_ignore("cheatsheet.pdf")
```

This way build should pass.

**Comment by jhk0530** [comment]
image

Build was successful with `usethis~` but i have note in check process

image

I'm trying to find what caused this

**Comment by JohnCoene** [comment]
Strange, looks like an encoding issue of `#`. I can pull on my end later today and see if I can fix this. I let you know.

**Comment by jhk0530** [comment]
It seems that **unexpected** word caused this.
in `R/waiter.R` line 31, 36
image

and `R/waitress` line 30
image

I don't know what's that **red dot** means, maybe some icon or font?
but I think it's fine to remove them. as just `whitespace`

so after delete 3 "broken word", I re-built package, re-write manual with roxygen2 and checked which didn't make any problem. but still warning I can't understand.

image

**Comment by JohnCoene** [comment]
Awesome thanks! I guess it's good to merge, I'll do that later today. I'll link to the cheatsheet from the README and website too. Thank you again :)

**Pull request merged**
